insert into asignaturas (nombre, aula, lab, profesor, curso)
values ('Algebra lineal', 'A10 A11', null, 'Óscar Angulo', 1),
('Calculo', 'A10 A11', null, 'Óscar Arrita', 1),
('Circuitos eléctricos', 'A11 A10', '2L004', 'Evaristo J. Abril, Rubén M. Lorenzo, Ramón Durán', 1),
('Programación', 'TELEMATICA', '2L002', 'David González', 1),
('Introducción a la economía y a la empresa', 'A10 A11', null, 'Pedro Benito, Guillermo Aleixandre',1),
('Física', 'A11 A14 A107', null, 'Mª Ángeles García, Óscar Alejos',1),
('Fundamentos de electrónica', 'A11 A14 A107', null, 'José Emiliniao, María Aboy',1),
('Fundamentos de ordenadores y sistemas operativos', 'A11 A14', '2L002', 'Francisco Javier Díaz, Mario Martinez',1),
('Señales aleatorias y ruido', 'A11 A14 A107', '2L002', 'Juan Pablo Casaseca, Marcos Martin', 1),
('Sistemas lineales', 'A11 A14 A107', null, 'Carlos Alberola, Rodrigo de Luis García',1),
('Ampliación de matemáticas', 'A12 A14', null, 'Eduardo Cuesta Montero',2),
('Arquitectura de redes, sistemas y servicios', 'A12 A14', '2L001', 'Eduardo Gómez', 2),
('Circuitos electrónicos digitales', 'A12 A14', '1L007', 'Martín Jaraíz', 2),
('Circuitos electrónicos analógicos', 'A12 A14', 'LABORATORIO DE ELECTRONICA', 'Lourdes Enríquez, María Aboy', 2),
('Teoría de la comunicación', 'A12 A14', '2L003', 'Jesús Poza, Juan Pablo de Castro, María García', 2),
('Campos electromagnéticos', 'A12 A13', '2L005', 'María Jesús González, Juan Carlos García, Juan Ignacio Arribas', 2),
('Ingeniería de sistemas software', 'A12 A13', '2L009', 'Guillermo Vega, María Ángeles Pérez', 2),
('Redes y servicios telemáticos', 'A12 A13', '2L001', 'Jaime Gómez, Isabel de la Torre', 2),
('Sistemas de comunicación', 'A12 A13', null, 'Miguel López, Beatriz Sainz', 2),
('Sistemas electrónicos basados en microprocesador', 'A12 A13', '1L019', 'Ruth Pinacho, Luis Alberto Marqués', 2),
('Desarrollo de aplicaciones distribuidas', 'A13', '2L001', 'Jaime Gómez', 3),
('Fundamentos de transmisión por radio', 'A13', '2L004 2L005 2L008', 'Juan Blas Prieto', 3),
('Ingeniería de protocolos en redes telemáticas', 'A13', '2L009', 'Eduardo Gómez', 3),
('Subsistemas electrónicos de comunicaciones', 'A13', null, 'Luis Quintanilla', 3),
('Teoría de campos guiados', 'A13', null, 'Julio Sánchez, María Jesús González', 3),
('Administración y gestión de redes y servicios telemáticos', 'A10', '2L006', 'Federico Simmross, Eduardo Gómez', 3),
('Diseño de circuitos digitales para comunicaciones', 'A10', '1L019', 'Ruth Pinacho, Jesús M. Hernández', 3),
('Microelectrónica de radio frecuencia', 'A10', null, 'Luis Quintanilla', 3),
('Sistemas de comunicaciones guiadas', 'A10', '2L007', 'Ignacio de Miguel Jiménez, Ramón José Durán, Noemí Merayo', 3),
('Traramiento digital de la señal', 'A10', '2L008', 'Alberto Izquierdo', 3),
('Fundamentos de sonido e imagen', 'A10', '2L002', 'Pablo Casaseca, Juan Ignacio Arribas', 4),
('Instrumentación y equipos electrónicos', 'A10', '1L023', 'José Vicente Antón', 4),
('Métodos numéricos en telecomunicación', 'A10', '2L009', 'Óscar Angulo', 4),
('Diseño de circuitos integrados para comunicaciones', 'A10', '1L020', 'Héctor García', 4),
('Laboratorio de desarrollo de sistemas telemáticos', 'A10', '2L003', 'Míriam Antón, María Ángeles Pérez', 4),
('Ingeniería de tráfico en redes telemáticas', 'A10', '2L009', 'Juan Ignacio Asensio', 4),
('Teoría de la detección y estimación', 'A10', '2L002', 'Carlos Alberola, César Gutiérrez', 4),
('Desarrollo práctico de sistemas electrónicos', 'A10', '1L019', 'Jesús M. Hernández', 4),
('Laboratorio de administración y gestión de redes y servicios telemáticos', 'A10', '2L006','Federico Simmross, Sergio Serrano', 4),
('Sistemas de comunicaciones ópticas', 'A10', '2L009', 'Evaristo J. Abril, Ramón J. Durán, Noemí Merayo', 4),
('Sistemas de telecomunicación por radio', 'A10', '2L004 2L005', 'Ramón de la Rosa', 4);